package cmd

import (
	"fmt"
	"path/filepath"

	"github.com/spf13/cobra"

	"github.com/reloquent/reloquent/internal/config"
	"github.com/reloquent/reloquent/internal/schema"
	"github.com/reloquent/reloquent/internal/state"
)

var ingestFile string

var ingestCmd = &cobra.Command{
	Use:   "ingest",
	Short: "Import offline discovery output",
	Long:  `Import a schema discovery output file generated by the offline discovery script.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		s, err := schema.LoadYAML(ingestFile)
		if err != nil {
			return fmt.Errorf("loading schema from %s: %w", ingestFile, err)
		}

		fmt.Println(s.Summary())

		// Save schema to the standard location
		statePath := config.ExpandHome(state.DefaultPath)
		stateDir := filepath.Dir(statePath)
		schemaPath := filepath.Join(stateDir, "source-schema.yaml")
		if err := s.WriteYAML(schemaPath); err != nil {
			return fmt.Errorf("saving schema: %w", err)
		}

		// Update state
		st, err := state.Load("")
		if err != nil {
			return fmt.Errorf("loading state: %w", err)
		}
		st.SchemaPath = schemaPath
		st.CompleteStep(state.StepSourceConnection, state.StepTargetConnection)
		if err := st.Save(""); err != nil {
			return fmt.Errorf("saving state: %w", err)
		}

		fmt.Printf("\nSchema ingested from %s\n", ingestFile)
		fmt.Printf("Schema saved to %s\n", schemaPath)
		fmt.Println("Source connection step marked complete. Run the wizard to continue from target connection.")

		return nil
	},
}

func init() {
	ingestCmd.Flags().StringVar(&ingestFile, "file", "", "path to discovery output file")
	_ = ingestCmd.MarkFlagRequired("file")
	rootCmd.AddCommand(ingestCmd)
}
